# https://starship.rs/config/#prompt
# Fonts: https://github.com/ryanoasis/nerd-fonts

# Disable the newline at the start of the prompt
add_newline = true

# Overwrite a default_prompt_order and  use custom prompt_order
prompt_order=["username","hostname","directory", "git_branch", "time", "python",  "line_break", "character"]

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[directory]
truncation_length = 5
truncate_to_repo = false

[username]
disabled = false
show_always = true

[hostname]
ssh_only = true
prefix = "⟪"
suffix = "⟫"
trim_at = ".companyname.com"
disabled = false

[git_branch]
symbol = " "
truncation_length = 10
truncation_symbol = ""

[time]
disabled = false
format = "🕙[ %T ]"
utc_time_offset = -5
style = "yellow"

[line_break]
disabled = false
